set(_source "${CMAKE_CURRENT_SOURCE_DIR}/paraview")
set(_build "${CMAKE_CURRENT_BINARY_DIR}/paraview")

unset(_deps)

ExternalProject_Add(paraview
  SOURCE_DIR ${_source}
  BINARY_DIR ${_build}
  INSTALL_COMMAND ""
  CMAKE_CACHE_ARGS
    ${TomvizSuper_DEFAULT_ARGS}
    -DBUILD_TESTING:BOOL=OFF
    -DPARAVIEW_BUILD_SHARED_LIBS:BOOL=ON
    -DPARAVIEW_ENABLE_CATALYST:BOOL=OFF
    -DPARAVIEW_ENABLE_PYTHON:BOOL=ON
    -DPARAVIEW_ENABLE_WEB:BOOL=OFF
    -DPARAVIEW_ENABLE_EMBEDDED_DOCUMENTATION:BOOL=OFF
    -DPARAVIEW_USE_QTHELP:BOOL=OFF
    -DPARAVIEW_PLUGINS_DEFAULT:BOOL=OFF
    -DPARAVIEW_USE_VTKM:BOOL=OFF
    #-DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB
    -DVTK_PYTHON_VERSION:STRING=3
    -DVTK_PYTHON_FULL_THREADSAFE:BOOL=ON
    -DVTK_NO_PYTHON_THREADS:BOOL=OFF
  DEPENDS
    ${_deps}
)
